### ISSUE TITLE
[Bug] Broken icon

### ISSUE THREAD

**Issue by yalov** [DefiantZombie/Collide-o-Scope#7]
Version 1.2.2 has broken icons, which showed up as red question. 

![](https://i.imgur.com/mQDoX9M.png)

Replacing with the icons, from last version fixes the problem.

**Comment by DefiantZombie** [comment]
Thank you! It looks like another artifact of an issue I had in my dev setup.

**Comment by DefiantZombie** [comment]
Fixed with ab15d3c1c42bbf596459dd131b8b032e51290951
